# Copyright 2018 AT&T Intellectual Property.  All other rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Set zuul_site_mirror_fqdn from env var if not defined
  when: zuul_site_mirror_fqdn is not defined
  set_fact:
    zuul_site_mirror_fqdn: "{{ lookup('env','zuul_site_mirror_fqdn') }}"

- name: Checkout treasuremap v1.9 branch
  shell: |
    set -xe;
    git checkout v1.9
  environment:
    zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
  args:
    chdir: "{{ zuul.project.src_dir }}/{{ zuul_treasuremap_relative_path | default('') }}"

- name: Deploy Kubernetes
  shell: |
    set -xe;
    ./tools/deployment/airskiff/developer/010-deploy-k8s.sh
  environment:
    zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
  args:
    chdir: "{{ zuul.project.src_dir }}/{{ zuul_treasuremap_relative_path | default('') }}"

- name: Make OSH charts
  shell: |
    set -xe
    make all
  environment:
    zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
  args:
    chdir: "{{ zuul.project.src_dir }}/{{ zuul_osh_relative_path | default('') }}"

- name: Make OSH_INFRA charts
  shell: |
    set -xe
    make all
  environment:
    zuul_site_mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
  args:
    chdir: "{{ zuul.project.src_dir }}/{{ zuul_osh_infra_relative_path | default('') }}"


- name: Setup docker-based openstack client
  shell: |
    set -xe;
    ./tools/deployment/airskiff/developer/020-setup-client.sh
  args:
    chdir: "{{ zuul.project.src_dir }}/{{ zuul_treasuremap_relative_path | default('') }}"

- name: Deploy Ingress
  shell: |
    set -xe;
    ./tools/deployment/component/common/ingress.sh
  args:
    chdir: "{{ zuul.project.src_dir }}/{{ zuul_osh_relative_path | default('') }}"

- name: Deploy NFS
  shell: |
    set -xe;
    ./tools/deployment/component/nfs-provisioner/nfs-provisioner.sh
  args:
    chdir: "{{ zuul.project.src_dir }}/{{ zuul_osh_relative_path | default('') }}"

- name: Deploy MariaDB
  shell: |
    set -xe;
    ./tools/deployment/component/common/mariadb.sh
  args:
    chdir: "{{ zuul.project.src_dir }}/{{ zuul_osh_relative_path | default('') }}"

- name: Deploy RabbitMQ
  shell: |
    set -xe;
    ./tools/deployment/component/common/rabbitmq.sh
  args:
    chdir: "{{ zuul.project.src_dir }}/{{ zuul_osh_relative_path | default('') }}"

- name: Deploy Memcached
  shell: |
    set -xe;
    ./tools/deployment/component/common/memcached.sh
  args:
    chdir: "{{ zuul.project.src_dir }}/{{ zuul_osh_relative_path | default('') }}"

- name: Deploy Keystone
  shell: |
    set -xe;
    ./tools/deployment/component/keystone/keystone.sh
  args:
    chdir: "{{ zuul.project.src_dir }}/{{ zuul_osh_relative_path | default('') }}"