# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $envAll := . }}

{{- if empty .Values.conf.deckhand.keystone_authtoken.auth_uri -}}
{{- tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup" | set .Values.conf.deckhand.keystone_authtoken "auth_uri" | quote | trunc 0 -}}
{{- end -}}

# FIXME fix for broken keystonemiddleware oslo config gen in newton - will remove in future
{{- if empty .Values.conf.deckhand.keystone_authtoken.auth_url -}}
{{- tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.deckhand.keystone_authtoken "auth_url" | quote | trunc 0 -}}
{{- end -}}

# Add endpoint URI lookup for Deckhand Postgresql DB Connection
{{- if empty .Values.conf.deckhand.database.connection -}}
{{- tuple "postgresql" "internal" "user" "postgresql" . | include "helm-toolkit.endpoints.authenticated_endpoint_uri_lookup"| set .Values.conf.deckhand.database "connection" | quote | trunc 0 -}}
{{- end -}}

# Add endpoint URI lookup for memcached servers Connection
{{- if empty .Values.conf.deckhand.keystone_authtoken.memcached_servers -}}
{{- tuple "oslo_cache" "internal" "memcache" . | include "helm-toolkit.endpoints.host_and_port_endpoint_uri_lookup" | set .Values.conf.deckhand.keystone_authtoken "memcached_servers" | quote | trunc 0 -}}
{{- end -}}

{{- $userIdentity := .Values.endpoints.identity.auth.user -}}

{{- if empty .Values.conf.deckhand.keystone_authtoken.project_name -}}
{{- set .Values.conf.deckhand.keystone_authtoken "project_name" $userIdentity.project_name | quote | trunc 0 -}}
{{- end -}}
{{- if empty .Values.conf.deckhand.keystone_authtoken.project_domain_name -}}
{{- set .Values.conf.deckhand.keystone_authtoken "project_domain_name" $userIdentity.project_domain_name | quote | trunc 0 -}}
{{- end -}}
{{- if empty .Values.conf.deckhand.keystone_authtoken.user_domain_name -}}
{{- set .Values.conf.deckhand.keystone_authtoken "user_domain_name" $userIdentity.user_domain_name | quote | trunc 0 -}}
{{- end -}}
{{- if empty .Values.conf.deckhand.keystone_authtoken.username -}}
{{- set .Values.conf.deckhand.keystone_authtoken "username" $userIdentity.username | quote | trunc 0 -}}
{{- end -}}
{{- if empty .Values.conf.deckhand.keystone_authtoken.password -}}
{{- set .Values.conf.deckhand.keystone_authtoken "password" $userIdentity.password | quote | trunc 0 -}}
{{- end -}}

# Set a random string as secret key.
{{- if empty .Values.conf.deckhand.keystone_authtoken.memcache_secret_key -}}
{{- randAlphaNum 64 | set .Values.conf.deckhand.keystone_authtoken "memcache_secret_key" | quote | trunc 0 -}}
{{- end -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deckhand-etc
data:
  deckhand.conf: |+
{{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.deckhand | indent 4 }}
  logging.conf: |+
{{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.logging | indent 4 }}
  deckhand-paste.ini: |+
{{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.paste | indent 4 }}
  policy.yaml: |+
{{ toYaml .Values.conf.policy | indent 4 }}
